name: ai.calcimetry
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - matplotlib
  - scipy
  - pandas
  - pymongo
  - xlrd
  - scikit-image
  - scikit-learn
  - seaborn
  - pip
    # notebooks:
  - jupyterlab
  - ipywidgets
  - voila
  - rise
    # speed
  - mamba
  - pip:
      - opencv-python
      - piq
      - flake8

